<?php

namespace Container2tJSjeh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ozmf7uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ozmf7u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ozmf7u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'vr' => ['privates', 'App\\Repository\\VOITURERepository', 'getVOITURERepositoryService', true],
        ], [
            'em' => '?',
            'vr' => 'App\\Repository\\VOITURERepository',
        ]);
    }
}
