<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2tJSjeh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2tJSjeh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2tJSjeh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2tJSjeh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2tJSjeh\App_KernelDevDebugContainer([
    'container.build_hash' => '2tJSjeh',
    'container.build_id' => 'e828896a',
    'container.build_time' => 1700735152,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2tJSjeh');
